/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DisputeStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Dispute = IDL.Record({
  'status' : DisputeStatus,
  'description' : IDL.Text,
  'session' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TeacherProfile = IDL.Record({
  'bio' : IDL.Text,
  'timezone' : IDL.Text,
  'teachingStyle' : IDL.Text,
  'grades' : IDL.Vec(IDL.Text),
  'subjects' : IDL.Vec(IDL.Text),
  'hourlyRate' : IDL.Float64,
  'languages' : IDL.Vec(IDL.Text),
  'fullName' : IDL.Text,
  'qualifications' : IDL.Text,
  'averageRating' : IDL.Float64,
  'experienceYears' : IDL.Nat,
  'isVisible' : IDL.Bool,
  'certifications' : IDL.Text,
  'demoVideo' : IDL.Text,
});
export const SessionStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const SessionType = IDL.Variant({
  'group' : IDL.Null,
  'oneToOne' : IDL.Null,
});
export const Session = IDL.Record({
  'status' : SessionStatus,
  'duration' : IDL.Nat,
  'subject' : IDL.Text,
  'sessionType' : SessionType,
  'scheduledTime' : IDL.Int,
  'teacher' : IDL.Principal,
  'meetingLink' : IDL.Text,
  'grade' : IDL.Text,
  'notes' : IDL.Text,
  'studentCount' : IDL.Nat,
});
export const WeeklySnapshot = IDL.Record({
  'topSubjects' : IDL.Vec(IDL.Text),
  'activeSessions' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
  'weekStart' : IDL.Int,
});
export const TeacherStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'suspended' : IDL.Null,
});
export const AdminTeacherInfo = IDL.Record({
  'status' : TeacherStatus,
  'principal' : IDL.Principal,
  'profile' : TeacherProfile,
});
export const AdminPanel = IDL.Record({
  'disputes' : IDL.Vec(Dispute),
  'teachers' : IDL.Vec(AdminTeacherInfo),
  'commissionRate' : IDL.Float64,
});
export const PerformanceRecord = IDL.Record({
  'subject' : IDL.Text,
  'date' : IDL.Int,
  'attended' : IDL.Bool,
  'ratingGiven' : IDL.Float64,
  'grade' : IDL.Text,
  'sessionId' : IDL.Nat,
});
export const StudentProfile = IDL.Record({
  'bio' : IDL.Text,
  'subjects' : IDL.Vec(IDL.Text),
  'fullName' : IDL.Text,
  'grade' : IDL.Text,
});
export const UserActivity = IDL.Record({
  'action' : IDL.Text,
  'detail' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserRecord = IDL.Record({
  'principal' : IDL.Principal,
  'joinTimestamp' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isSuspended' : IDL.Bool,
});
export const Analytics = IDL.Record({
  'topSubjects' : IDL.Vec(IDL.Text),
  'growthPercentage' : IDL.Float64,
  'averageRating' : IDL.Float64,
  'earningsPerMonth' : IDL.Vec(IDL.Float64),
  'totalSessions' : IDL.Nat,
  'retentionRate' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Transaction = IDL.Record({
  'subject' : IDL.Text,
  'netPayout' : IDL.Float64,
  'date' : IDL.Int,
  'student' : IDL.Text,
  'commissionRate' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const Wallet = IDL.Record({
  'pendingPayments' : IDL.Float64,
  'availableBalance' : IDL.Float64,
  'totalEarnings' : IDL.Float64,
  'transactions' : IDL.Vec(Transaction),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SearchParams = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'maxHourlyRate' : IDL.Opt(IDL.Float64),
  'language' : IDL.Opt(IDL.Text),
  'minExperience' : IDL.Opt(IDL.Nat),
  'grade' : IDL.Opt(IDL.Text),
  'onlyVisible' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDispute' : IDL.Func([Dispute], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func([TeacherProfile], [], []),
  'createSession' : IDL.Func([Session], [IDL.Nat], []),
  'generateWeeklySnapshot' : IDL.Func([], [WeeklySnapshot], []),
  'getAdminPanel' : IDL.Func([], [AdminPanel], ['query']),
  'getAllPerformanceRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PerformanceRecord)))],
      ['query'],
    ),
  'getAllStudentProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
      ['query'],
    ),
  'getAllUserActivities' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UserActivity)))],
      ['query'],
    ),
  'getAllUserRecords' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'getAnalytics' : IDL.Func([], [IDL.Opt(Analytics)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestWeeklySnapshot' : IDL.Func(
      [],
      [IDL.Opt(WeeklySnapshot)],
      ['query'],
    ),
  'getPerformanceRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PerformanceRecord)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(TeacherProfile)], ['query']),
  'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getTeacherProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TeacherProfile)],
      ['query'],
    ),
  'getUserActivity' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UserActivity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletSummary' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getWeeklySnapshots' : IDL.Func([], [IDL.Vec(WeeklySnapshot)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveTeachers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listAllTeachersAdmin' : IDL.Func([], [IDL.Vec(AdminTeacherInfo)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listSessions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Session))],
      ['query'],
    ),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'logUserActivity' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordWeeklySnapshot' : IDL.Func([WeeklySnapshot], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'searchTeachers' : IDL.Func(
      [SearchParams],
      [IDL.Vec(TeacherProfile)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setCommissionRate' : IDL.Func([IDL.Float64], [], []),
  'submitPerformanceRecord' : IDL.Func([PerformanceRecord], [], []),
  'submitWithdrawalRequest' : IDL.Func([IDL.Float64], [], []),
  'toggleUserSuspension' : IDL.Func([IDL.Principal], [], []),
  'updateProfile' : IDL.Func([TeacherProfile], [], []),
  'updateSession' : IDL.Func([IDL.Nat, Session], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DisputeStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Dispute = IDL.Record({
    'status' : DisputeStatus,
    'description' : IDL.Text,
    'session' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TeacherProfile = IDL.Record({
    'bio' : IDL.Text,
    'timezone' : IDL.Text,
    'teachingStyle' : IDL.Text,
    'grades' : IDL.Vec(IDL.Text),
    'subjects' : IDL.Vec(IDL.Text),
    'hourlyRate' : IDL.Float64,
    'languages' : IDL.Vec(IDL.Text),
    'fullName' : IDL.Text,
    'qualifications' : IDL.Text,
    'averageRating' : IDL.Float64,
    'experienceYears' : IDL.Nat,
    'isVisible' : IDL.Bool,
    'certifications' : IDL.Text,
    'demoVideo' : IDL.Text,
  });
  const SessionStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const SessionType = IDL.Variant({
    'group' : IDL.Null,
    'oneToOne' : IDL.Null,
  });
  const Session = IDL.Record({
    'status' : SessionStatus,
    'duration' : IDL.Nat,
    'subject' : IDL.Text,
    'sessionType' : SessionType,
    'scheduledTime' : IDL.Int,
    'teacher' : IDL.Principal,
    'meetingLink' : IDL.Text,
    'grade' : IDL.Text,
    'notes' : IDL.Text,
    'studentCount' : IDL.Nat,
  });
  const WeeklySnapshot = IDL.Record({
    'topSubjects' : IDL.Vec(IDL.Text),
    'activeSessions' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
    'weekStart' : IDL.Int,
  });
  const TeacherStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const AdminTeacherInfo = IDL.Record({
    'status' : TeacherStatus,
    'principal' : IDL.Principal,
    'profile' : TeacherProfile,
  });
  const AdminPanel = IDL.Record({
    'disputes' : IDL.Vec(Dispute),
    'teachers' : IDL.Vec(AdminTeacherInfo),
    'commissionRate' : IDL.Float64,
  });
  const PerformanceRecord = IDL.Record({
    'subject' : IDL.Text,
    'date' : IDL.Int,
    'attended' : IDL.Bool,
    'ratingGiven' : IDL.Float64,
    'grade' : IDL.Text,
    'sessionId' : IDL.Nat,
  });
  const StudentProfile = IDL.Record({
    'bio' : IDL.Text,
    'subjects' : IDL.Vec(IDL.Text),
    'fullName' : IDL.Text,
    'grade' : IDL.Text,
  });
  const UserActivity = IDL.Record({
    'action' : IDL.Text,
    'detail' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserRecord = IDL.Record({
    'principal' : IDL.Principal,
    'joinTimestamp' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isSuspended' : IDL.Bool,
  });
  const Analytics = IDL.Record({
    'topSubjects' : IDL.Vec(IDL.Text),
    'growthPercentage' : IDL.Float64,
    'averageRating' : IDL.Float64,
    'earningsPerMonth' : IDL.Vec(IDL.Float64),
    'totalSessions' : IDL.Nat,
    'retentionRate' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Transaction = IDL.Record({
    'subject' : IDL.Text,
    'netPayout' : IDL.Float64,
    'date' : IDL.Int,
    'student' : IDL.Text,
    'commissionRate' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const Wallet = IDL.Record({
    'pendingPayments' : IDL.Float64,
    'availableBalance' : IDL.Float64,
    'totalEarnings' : IDL.Float64,
    'transactions' : IDL.Vec(Transaction),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SearchParams = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'maxHourlyRate' : IDL.Opt(IDL.Float64),
    'language' : IDL.Opt(IDL.Text),
    'minExperience' : IDL.Opt(IDL.Nat),
    'grade' : IDL.Opt(IDL.Text),
    'onlyVisible' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDispute' : IDL.Func([Dispute], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func([TeacherProfile], [], []),
    'createSession' : IDL.Func([Session], [IDL.Nat], []),
    'generateWeeklySnapshot' : IDL.Func([], [WeeklySnapshot], []),
    'getAdminPanel' : IDL.Func([], [AdminPanel], ['query']),
    'getAllPerformanceRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PerformanceRecord)))],
        ['query'],
      ),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
        ['query'],
      ),
    'getAllUserActivities' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UserActivity)))],
        ['query'],
      ),
    'getAllUserRecords' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'getAnalytics' : IDL.Func([], [IDL.Opt(Analytics)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestWeeklySnapshot' : IDL.Func(
        [],
        [IDL.Opt(WeeklySnapshot)],
        ['query'],
      ),
    'getPerformanceRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PerformanceRecord)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(TeacherProfile)], ['query']),
    'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getTeacherProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TeacherProfile)],
        ['query'],
      ),
    'getUserActivity' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserActivity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletSummary' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getWeeklySnapshots' : IDL.Func([], [IDL.Vec(WeeklySnapshot)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveTeachers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listAllTeachersAdmin' : IDL.Func(
        [],
        [IDL.Vec(AdminTeacherInfo)],
        ['query'],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listSessions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Session))],
        ['query'],
      ),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'logUserActivity' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordWeeklySnapshot' : IDL.Func([WeeklySnapshot], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'searchTeachers' : IDL.Func(
        [SearchParams],
        [IDL.Vec(TeacherProfile)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setCommissionRate' : IDL.Func([IDL.Float64], [], []),
    'submitPerformanceRecord' : IDL.Func([PerformanceRecord], [], []),
    'submitWithdrawalRequest' : IDL.Func([IDL.Float64], [], []),
    'toggleUserSuspension' : IDL.Func([IDL.Principal], [], []),
    'updateProfile' : IDL.Func([TeacherProfile], [], []),
    'updateSession' : IDL.Func([IDL.Nat, Session], [], []),
  });
};

export const init = ({ IDL }) => { return []; };