/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPanel {
  'disputes' : Array<Dispute>,
  'teachers' : Array<AdminTeacherInfo>,
  'commissionRate' : number,
}
export interface AdminTeacherInfo {
  'status' : TeacherStatus,
  'principal' : Principal,
  'profile' : TeacherProfile,
}
export interface Analytics {
  'topSubjects' : Array<string>,
  'growthPercentage' : number,
  'averageRating' : number,
  'earningsPerMonth' : Array<number>,
  'totalSessions' : bigint,
  'retentionRate' : number,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Dispute {
  'status' : DisputeStatus,
  'description' : string,
  'session' : bigint,
}
export type DisputeStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'rejected' : null };
export interface PerformanceRecord {
  'subject' : string,
  'date' : bigint,
  'attended' : boolean,
  'ratingGiven' : number,
  'grade' : string,
  'sessionId' : bigint,
}
export interface SearchParams {
  'subject' : [] | [string],
  'maxHourlyRate' : [] | [number],
  'language' : [] | [string],
  'minExperience' : [] | [bigint],
  'grade' : [] | [string],
  'onlyVisible' : [] | [boolean],
}
export interface Session {
  'status' : SessionStatus,
  'duration' : bigint,
  'subject' : string,
  'sessionType' : SessionType,
  'scheduledTime' : bigint,
  'teacher' : Principal,
  'meetingLink' : string,
  'grade' : string,
  'notes' : string,
  'studentCount' : bigint,
}
export type SessionStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type SessionType = { 'group' : null } |
  { 'oneToOne' : null };
export interface StudentProfile {
  'bio' : string,
  'subjects' : Array<string>,
  'fullName' : string,
  'grade' : string,
}
export interface TeacherProfile {
  'bio' : string,
  'timezone' : string,
  'teachingStyle' : string,
  'grades' : Array<string>,
  'subjects' : Array<string>,
  'hourlyRate' : number,
  'languages' : Array<string>,
  'fullName' : string,
  'qualifications' : string,
  'averageRating' : number,
  'experienceYears' : bigint,
  'isVisible' : boolean,
  'certifications' : string,
  'demoVideo' : string,
}
export type TeacherStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'suspended' : null };
export interface Transaction {
  'subject' : string,
  'netPayout' : number,
  'date' : bigint,
  'student' : string,
  'commissionRate' : number,
  'amount' : number,
}
export interface UserActivity {
  'action' : string,
  'detail' : string,
  'timestamp' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'role' : string }
export interface UserRecord {
  'principal' : Principal,
  'joinTimestamp' : bigint,
  'name' : string,
  'role' : string,
  'isSuspended' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'pendingPayments' : number,
  'availableBalance' : number,
  'totalEarnings' : number,
  'transactions' : Array<Transaction>,
}
export interface WeeklySnapshot {
  'topSubjects' : Array<string>,
  'activeSessions' : bigint,
  'totalUsers' : bigint,
  'totalEarnings' : number,
  'weekStart' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDispute' : ActorMethod<[Dispute], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<[TeacherProfile], undefined>,
  'createSession' : ActorMethod<[Session], bigint>,
  'generateWeeklySnapshot' : ActorMethod<[], WeeklySnapshot>,
  'getAdminPanel' : ActorMethod<[], AdminPanel>,
  'getAllPerformanceRecords' : ActorMethod<
    [],
    Array<[Principal, Array<PerformanceRecord>]>
  >,
  'getAllStudentProfiles' : ActorMethod<[], Array<[Principal, StudentProfile]>>,
  'getAllUserActivities' : ActorMethod<
    [],
    Array<[Principal, Array<UserActivity>]>
  >,
  'getAllUserRecords' : ActorMethod<[], Array<UserRecord>>,
  'getAnalytics' : ActorMethod<[], [] | [Analytics]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestWeeklySnapshot' : ActorMethod<[], [] | [WeeklySnapshot]>,
  'getPerformanceRecords' : ActorMethod<[Principal], Array<PerformanceRecord>>,
  'getProfile' : ActorMethod<[], [] | [TeacherProfile]>,
  'getStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getTeacherProfile' : ActorMethod<[Principal], [] | [TeacherProfile]>,
  'getUserActivity' : ActorMethod<[Principal], Array<UserActivity>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletSummary' : ActorMethod<[], [] | [Wallet]>,
  'getWeeklySnapshots' : ActorMethod<[], Array<WeeklySnapshot>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listActiveTeachers' : ActorMethod<[], Array<Principal>>,
  'listAllTeachersAdmin' : ActorMethod<[], Array<AdminTeacherInfo>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listSessions' : ActorMethod<[], Array<[bigint, Session]>>,
  'listTransactions' : ActorMethod<[], Array<Transaction>>,
  'logUserActivity' : ActorMethod<[string, string], undefined>,
  'recordWeeklySnapshot' : ActorMethod<[WeeklySnapshot], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'searchTeachers' : ActorMethod<[SearchParams], Array<TeacherProfile>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setCommissionRate' : ActorMethod<[number], undefined>,
  'submitPerformanceRecord' : ActorMethod<[PerformanceRecord], undefined>,
  'submitWithdrawalRequest' : ActorMethod<[number], undefined>,
  'toggleUserSuspension' : ActorMethod<[Principal], undefined>,
  'updateProfile' : ActorMethod<[TeacherProfile], undefined>,
  'updateSession' : ActorMethod<[bigint, Session], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];