/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserActivity {
    action: string;
    detail: string;
    timestamp: bigint;
}
export interface AdminPanel {
    disputes: Array<Dispute>;
    teachers: Array<AdminTeacherInfo>;
    commissionRate: number;
}
export interface AdminTeacherInfo {
    status: TeacherStatus;
    principal: Principal;
    profile: TeacherProfile;
}
export interface SearchParams {
    subject?: string;
    maxHourlyRate?: number;
    language?: string;
    minExperience?: bigint;
    grade?: string;
    onlyVisible?: boolean;
}
export interface UserRecord {
    principal: Principal;
    joinTimestamp: bigint;
    name: string;
    role: string;
    isSuspended: boolean;
}
export interface Transaction {
    subject: string;
    netPayout: number;
    date: bigint;
    student: string;
    commissionRate: number;
    amount: number;
}
export interface TeacherProfile {
    bio: string;
    timezone: string;
    teachingStyle: string;
    grades: Array<string>;
    subjects: Array<string>;
    hourlyRate: number;
    languages: Array<string>;
    fullName: string;
    qualifications: string;
    averageRating: number;
    experienceYears: bigint;
    isVisible: boolean;
    certifications: string;
    demoVideo: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Wallet {
    pendingPayments: number;
    availableBalance: number;
    totalEarnings: number;
    transactions: Array<Transaction>;
}
export interface StudentProfile {
    bio: string;
    subjects: Array<string>;
    fullName: string;
    grade: string;
}
export interface Session {
    status: SessionStatus;
    duration: bigint;
    subject: string;
    sessionType: SessionType;
    scheduledTime: bigint;
    teacher: Principal;
    meetingLink: string;
    grade: string;
    notes: string;
    studentCount: bigint;
}
export interface PerformanceRecord {
    subject: string;
    date: bigint;
    attended: boolean;
    ratingGiven: number;
    grade: string;
    sessionId: bigint;
}
export interface Dispute {
    status: DisputeStatus;
    description: string;
    session: bigint;
}
export interface Analytics {
    topSubjects: Array<string>;
    growthPercentage: number;
    averageRating: number;
    earningsPerMonth: Array<number>;
    totalSessions: bigint;
    retentionRate: number;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface WeeklySnapshot {
    topSubjects: Array<string>;
    activeSessions: bigint;
    totalUsers: bigint;
    totalEarnings: number;
    weekStart: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum DisputeStatus {
    resolved = "resolved",
    open = "open",
    rejected = "rejected"
}
export enum SessionStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum SessionType {
    group = "group",
    oneToOne = "oneToOne"
}
export enum TeacherStatus {
    pending = "pending",
    approved = "approved",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDispute(dispute: Dispute): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProfile(profile: TeacherProfile): Promise<void>;
    createSession(session: Session): Promise<bigint>;
    generateWeeklySnapshot(): Promise<WeeklySnapshot>;
    getAdminPanel(): Promise<AdminPanel>;
    getAllPerformanceRecords(): Promise<Array<[Principal, Array<PerformanceRecord>]>>;
    getAllStudentProfiles(): Promise<Array<[Principal, StudentProfile]>>;
    getAllUserActivities(): Promise<Array<[Principal, Array<UserActivity>]>>;
    getAllUserRecords(): Promise<Array<UserRecord>>;
    getAnalytics(): Promise<Analytics | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLatestWeeklySnapshot(): Promise<WeeklySnapshot | null>;
    getPerformanceRecords(user: Principal): Promise<Array<PerformanceRecord>>;
    getProfile(): Promise<TeacherProfile | null>;
    getStudentProfile(): Promise<StudentProfile | null>;
    getTeacherProfile(teacher: Principal): Promise<TeacherProfile | null>;
    getUserActivity(user: Principal): Promise<Array<UserActivity>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletSummary(): Promise<Wallet | null>;
    getWeeklySnapshots(): Promise<Array<WeeklySnapshot>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listActiveTeachers(): Promise<Array<Principal>>;
    listAllTeachersAdmin(): Promise<Array<AdminTeacherInfo>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listSessions(): Promise<Array<[bigint, Session]>>;
    listTransactions(): Promise<Array<Transaction>>;
    logUserActivity(action: string, detail: string): Promise<void>;
    recordWeeklySnapshot(snapshot: WeeklySnapshot): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveStudentProfile(profile: StudentProfile): Promise<void>;
    searchTeachers(searchParams: SearchParams): Promise<Array<TeacherProfile>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setCommissionRate(rate: number): Promise<void>;
    submitPerformanceRecord(record: PerformanceRecord): Promise<void>;
    submitWithdrawalRequest(amount: number): Promise<void>;
    toggleUserSuspension(principal: Principal): Promise<void>;
    updateProfile(profile: TeacherProfile): Promise<void>;
    updateSession(id: bigint, session: Session): Promise<void>;
}
import type { AdminPanel as _AdminPanel, AdminTeacherInfo as _AdminTeacherInfo, Analytics as _Analytics, ApprovalStatus as _ApprovalStatus, Dispute as _Dispute, DisputeStatus as _DisputeStatus, SearchParams as _SearchParams, Session as _Session, SessionStatus as _SessionStatus, SessionType as _SessionType, StudentProfile as _StudentProfile, TeacherProfile as _TeacherProfile, TeacherStatus as _TeacherStatus, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, Wallet as _Wallet, WeeklySnapshot as _WeeklySnapshot } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDispute(arg0: Dispute): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDispute(to_candid_Dispute_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDispute(to_candid_Dispute_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: TeacherProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0);
            return result;
        }
    }
    async createSession(arg0: Session): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(to_candid_Session_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(to_candid_Session_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateWeeklySnapshot(): Promise<WeeklySnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.generateWeeklySnapshot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateWeeklySnapshot();
            return result;
        }
    }
    async getAdminPanel(): Promise<AdminPanel> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPanel();
                return from_candid_AdminPanel_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPanel();
            return from_candid_AdminPanel_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPerformanceRecords(): Promise<Array<[Principal, Array<PerformanceRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPerformanceRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPerformanceRecords();
            return result;
        }
    }
    async getAllStudentProfiles(): Promise<Array<[Principal, StudentProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentProfiles();
            return result;
        }
    }
    async getAllUserActivities(): Promise<Array<[Principal, Array<UserActivity>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserActivities();
            return result;
        }
    }
    async getAllUserRecords(): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserRecords();
            return result;
        }
    }
    async getAnalytics(): Promise<Analytics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestWeeklySnapshot(): Promise<WeeklySnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestWeeklySnapshot();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestWeeklySnapshot();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceRecords(arg0: Principal): Promise<Array<PerformanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceRecords(arg0);
            return result;
        }
    }
    async getProfile(): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherProfile(arg0: Principal): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserActivity(arg0: Principal): Promise<Array<UserActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivity(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletSummary(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletSummary();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletSummary();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklySnapshots(): Promise<Array<WeeklySnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySnapshots();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listActiveTeachers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveTeachers();
            return result;
        }
    }
    async listAllTeachersAdmin(): Promise<Array<AdminTeacherInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTeachersAdmin();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTeachersAdmin();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSessions(): Promise<Array<[bigint, Session]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactions();
            return result;
        }
    }
    async logUserActivity(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logUserActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logUserActivity(arg0, arg1);
            return result;
        }
    }
    async recordWeeklySnapshot(arg0: WeeklySnapshot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWeeklySnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWeeklySnapshot(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfile(arg0);
            return result;
        }
    }
    async searchTeachers(arg0: SearchParams): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeachers(to_candid_SearchParams_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeachers(to_candid_SearchParams_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setCommissionRate(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCommissionRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCommissionRate(arg0);
            return result;
        }
    }
    async submitPerformanceRecord(arg0: PerformanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPerformanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPerformanceRecord(arg0);
            return result;
        }
    }
    async submitWithdrawalRequest(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(arg0);
            return result;
        }
    }
    async toggleUserSuspension(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserSuspension(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserSuspension(arg0);
            return result;
        }
    }
    async updateProfile(arg0: TeacherProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
    async updateSession(arg0: bigint, arg1: Session): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSession(arg0, to_candid_Session_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSession(arg0, to_candid_Session_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminPanel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminPanel): AdminPanel {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AdminTeacherInfo_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminTeacherInfo): AdminTeacherInfo {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_DisputeStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisputeStatus): DisputeStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Dispute_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dispute): Dispute {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TeacherStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeacherStatus): TeacherStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Analytics]): Analytics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeeklySnapshot]): WeeklySnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeacherProfile]): TeacherProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    disputes: Array<_Dispute>;
    teachers: Array<_AdminTeacherInfo>;
    commissionRate: number;
}): {
    disputes: Array<Dispute>;
    teachers: Array<AdminTeacherInfo>;
    commissionRate: number;
} {
    return {
        disputes: from_candid_vec_n15(_uploadFile, _downloadFile, value.disputes),
        teachers: from_candid_vec_n20(_uploadFile, _downloadFile, value.teachers),
        commissionRate: value.commissionRate
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DisputeStatus;
    description: string;
    session: bigint;
}): {
    status: DisputeStatus;
    description: string;
    session: bigint;
} {
    return {
        status: from_candid_DisputeStatus_n18(_uploadFile, _downloadFile, value.status),
        description: value.description,
        session: value.session
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TeacherStatus;
    principal: Principal;
    profile: _TeacherProfile;
}): {
    status: TeacherStatus;
    principal: Principal;
    profile: TeacherProfile;
} {
    return {
        status: from_candid_TeacherStatus_n23(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        profile: value.profile
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n36(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SessionStatus;
    duration: bigint;
    subject: string;
    sessionType: _SessionType;
    scheduledTime: bigint;
    teacher: Principal;
    meetingLink: string;
    grade: string;
    notes: string;
    studentCount: bigint;
}): {
    status: SessionStatus;
    duration: bigint;
    subject: string;
    sessionType: SessionType;
    scheduledTime: bigint;
    teacher: Principal;
    meetingLink: string;
    grade: string;
    notes: string;
    studentCount: bigint;
} {
    return {
        status: from_candid_SessionStatus_n42(_uploadFile, _downloadFile, value.status),
        duration: value.duration,
        subject: value.subject,
        sessionType: from_candid_SessionType_n44(_uploadFile, _downloadFile, value.sessionType),
        scheduledTime: value.scheduledTime,
        teacher: value.teacher,
        meetingLink: value.meetingLink,
        grade: value.grade,
        notes: value.notes,
        studentCount: value.studentCount
    };
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Session]): [bigint, Session] {
    return [
        value[0],
        from_candid_Session_n40(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
} | {
    rejected: null;
}): DisputeStatus {
    return "resolved" in value ? DisputeStatus.resolved : "open" in value ? DisputeStatus.open : "rejected" in value ? DisputeStatus.rejected : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    suspended: null;
}): TeacherStatus {
    return "pending" in value ? TeacherStatus.pending : "approved" in value ? TeacherStatus.approved : "suspended" in value ? TeacherStatus.suspended : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): SessionStatus {
    return "scheduled" in value ? SessionStatus.scheduled : "cancelled" in value ? SessionStatus.cancelled : "completed" in value ? SessionStatus.completed : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    group: null;
} | {
    oneToOne: null;
}): SessionType {
    return "group" in value ? SessionType.group : "oneToOne" in value ? SessionType.oneToOne : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dispute>): Array<Dispute> {
    return value.map((x)=>from_candid_Dispute_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminTeacherInfo>): Array<AdminTeacherInfo> {
    return value.map((x)=>from_candid_AdminTeacherInfo_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Session]>): Array<[bigint, Session]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_DisputeStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisputeStatus): _DisputeStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Dispute_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Dispute): _Dispute {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SearchParams_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchParams): _SearchParams {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_SessionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionStatus): _SessionStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_SessionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: DisputeStatus;
    description: string;
    session: bigint;
}): {
    status: _DisputeStatus;
    description: string;
    session: bigint;
} {
    return {
        status: to_candid_DisputeStatus_n3(_uploadFile, _downloadFile, value.status),
        description: value.description,
        session: value.session
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject?: string;
    maxHourlyRate?: number;
    language?: string;
    minExperience?: bigint;
    grade?: string;
    onlyVisible?: boolean;
}): {
    subject: [] | [string];
    maxHourlyRate: [] | [number];
    language: [] | [string];
    minExperience: [] | [bigint];
    grade: [] | [string];
    onlyVisible: [] | [boolean];
} {
    return {
        subject: value.subject ? candid_some(value.subject) : candid_none(),
        maxHourlyRate: value.maxHourlyRate ? candid_some(value.maxHourlyRate) : candid_none(),
        language: value.language ? candid_some(value.language) : candid_none(),
        minExperience: value.minExperience ? candid_some(value.minExperience) : candid_none(),
        grade: value.grade ? candid_some(value.grade) : candid_none(),
        onlyVisible: value.onlyVisible ? candid_some(value.onlyVisible) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SessionStatus;
    duration: bigint;
    subject: string;
    sessionType: SessionType;
    scheduledTime: bigint;
    teacher: Principal;
    meetingLink: string;
    grade: string;
    notes: string;
    studentCount: bigint;
}): {
    status: _SessionStatus;
    duration: bigint;
    subject: string;
    sessionType: _SessionType;
    scheduledTime: bigint;
    teacher: Principal;
    meetingLink: string;
    grade: string;
    notes: string;
    studentCount: bigint;
} {
    return {
        status: to_candid_SessionStatus_n9(_uploadFile, _downloadFile, value.status),
        duration: value.duration,
        subject: value.subject,
        sessionType: to_candid_SessionType_n11(_uploadFile, _downloadFile, value.sessionType),
        scheduledTime: value.scheduledTime,
        teacher: value.teacher,
        meetingLink: value.meetingLink,
        grade: value.grade,
        notes: value.notes,
        studentCount: value.studentCount
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == SessionStatus.scheduled ? {
        scheduled: null
    } : value == SessionStatus.cancelled ? {
        cancelled: null
    } : value == SessionStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    group: null;
} | {
    oneToOne: null;
} {
    return value == SessionType.group ? {
        group: null
    } : value == SessionType.oneToOne ? {
        oneToOne: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisputeStatus): {
    resolved: null;
} | {
    open: null;
} | {
    rejected: null;
} {
    return value == DisputeStatus.resolved ? {
        resolved: null
    } : value == DisputeStatus.open ? {
        open: null
    } : value == DisputeStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
